import Head from "next/head";
import conn from "../db/connection";
import Movie from "../models/Movie";
import Link from "next/link";
import Form from "../components/Form";

//{/*<Link href="#">href="/[id]/edit" as={`/${_id}/edit`}</Link>*/}
{/*<Link  href="#">href="/[id]"as={`/${_id}`}</Link>*/ }
export default function Home({ movies }) {
   
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className="container">
            <h1>Películas</h1>
            <div>
               <Form />
               <table >
                  <tr>
                     <th>Título</th>
                     <th>Año</th>
                     <th>Duración</th>
                     <th>Lenguaje</th>
                     <th>Lanzamiento</th>
                     <th>Ciudad</th>
                     <th>Editar</th>
                     <th>Eliminar</th>
                  </tr>
                  {movies.map(({ _id, title, year, duration, languaje, date, country }) => (
                     <tr key={_id}>
                        <td>{title}</td>
                        <td>{year}</td>
                        <td>{duration}</td>
                        <td>{languaje}</td>
                        <td>{date}</td>
                        <td>{country}</td>
                        <td><button>Editar</button></td>
                        <td><button>Eliminar</button></td>
                     </tr>
                  ))}
               </table>
            </div>
         </main>
      </>
   );
}

export async function getStaticProps() {
   try {
      conn();
      const result = await Movie.find({});
      const movies = result.map((doc) => {
         const movie = doc.toObject();
         movie._id = movie._id.toString();
         return movie;
      });
      return { props: { movies } };
   } catch (error) {
      console.log(error);
   }
}